apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
        - name: app
          image: busybox:1.34
          command: ["sh", "-c", "sleep 3600"]
# Note: missing securityContext.runAsNonRoot -> should be flagged by MVP scanner
