apiVersion: v1
kind: Pod
metadata:
  name: shadow-test-pod
  namespace: default
spec:
  containers:
  - name: attack-surface
    image: nginx:latest
    securityContext:
      privileged: true        # CRITICAL: Container escape possible!
      capabilities:
        add:
          - SYS_ADMIN        # CRITICAL: Full system capabilities
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock    # CRITICAL: Docker socket abuse!
    - name: host-root
      mountPath: /host                   # CRITICAL: Full host access!
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "AKIAIOSFODNN7EXAMPLE"      # CRITICAL: Hardcoded AWS key!
    - name: AWS_SECRET_ACCESS_KEY
      value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  hostNetwork: true          # HIGH: Host network access
  hostPID: true              # HIGH: Host PID namespace
  hostIPC: true              # HIGH: Host IPC namespace  
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: host-root
    hostPath:
      path: /
      type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dangerous-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin     # CRITICAL: Cluster admin access!
subjects:
- kind: ServiceAccount
  name: admin-sa
  namespace: default
